trigger:
  - main

resources:
  - repo: self

variables:
  - group: public-npm
  - name: vmImageName
    value: "ubuntu-latest"
  - name: envName
    value: "brandup-pages-ckeditor"
  - name: version-major
    value: "2"
  - name: version-minor
    value: "0"

name: $(version-major).$(version-minor).$(rev:r)

pool:
  vmImage: $(vmImageName)

stages:
  - stage: "Build"
    displayName: "Build"
    jobs:
      - job: "BuildNpm"
        displayName: "Build NPM"
        pool:
          vmImage: $(vmImageName)
          workspace:
            clean: all
        steps:
          - script: |
              echo "Begin build!"
              echo "build number - $(Build.BuildNumber)"
            displayName: "print variables"

          - checkout: self
            clean: "true"
            persistCredentials: "true"

          - task: "Npm@1"
            displayName: "npm install"
            inputs:
              command: "install"

          - task: "Npm@1"
            displayName: "npm build"
            inputs:
              command: "custom"
              customCommand: "run build"

          - task: "Npm@1"
            displayName: "npm version"
            inputs:
              command: "custom"
              customCommand: "npm version -- $(Build.BuildNumber)"

          - task: "Npm@1"
            displayName: "npm pack"
            inputs:
              command: custom
              customCommand: "npm pack --pack-destination $(Build.ArtifactStagingDirectory)"

          - publish: $(Build.ArtifactStagingDirectory)
            displayName: publish artifact
            condition: succeededOrFailed()
            artifact: npm

      - job: GitTag
        displayName: "Add git tag"
        dependsOn: [BuildNpm]
        condition: succeeded()
        steps:
          - checkout: self
            clean: "true"
            persistCredentials: "true"

          - pwsh: |
              git config --global user.name "AzureDevOps Agent"
              git tag "$(Build.BuildNumber)" --force
              git push origin "$(Build.BuildNumber)" --force
              Write-Output "Tagging $(Build.Repository.Name) with $(Build.BuildNumber)"
            displayName: set git tag

  - stage: Production
    displayName: Deploy stage
    dependsOn: Build
    jobs:
      - deployment: Production
        condition: succeeded()
        displayName: "NPM"
        pool:
          vmImage: $(vmImageName)
        environment: $(envName)
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  displayName: "download artifacts"
                  artifact: npm

                - task: ExtractFiles@1
                  displayName: "unzip brandup-pages-ckeditor"
                  inputs:
                    archiveFilePatterns: "$(Pipeline.Workspace)/npm/brandup-pages-ckeditor-$(Build.BuildNumber).tgz"
                    destinationFolder: "$(Pipeline.Workspace)/npm/brandup-pages-ckeditor"
                    cleanDestinationFolder: true
                    overwriteExistingFiles: true

                - task: Npm@1
                  displayName: "publish brandup-pages-ckeditor"
                  inputs:
                    command: publish
                    workingDir: "$(Pipeline.Workspace)/npm/brandup-pages-ckeditor/package"
                    publishEndpoint: "$(publish-npm-credentials)"